export const propertyTypesConst = [
    { value: 'apartamento', name: 'Apartamento' },
    { value: 'casadecondominio', name: 'Casa de condomínio' },
    { value: 'casadevila', name: 'Casa de vila' },
    { value: 'studio', name: 'Studio' },
    { value: 'kitnet', name: 'Kitnet' },
    { value: 'cobertura', name: 'Cobertura' },
    { value: 'flat', name: 'Flat' },
    { value: 'loft', name: 'Loft' },
    { value: 'ground', name: 'Terreno' },
    { value: 'comercial', name: 'Comercial' },
    { value: 'farm', name: 'Chácara' },
    { value: 'batch', name: 'Lote' },
    { value: 'casacomercial', name: 'Casa comercial' },
    { value: 'garagem', name: 'Garagem' },
    { value: 'pontocomercial', name: 'Ponto comercial' },
    { value: 'conjuntocomercial', name: 'Conjunto / Sala comercial' },
    { value: 'loja', name: 'Loja' },
    { value: 'salao', name: 'Salão' },
    { value: 'galpao', name: 'Galpão' },
    { value: 'deposito', name: 'Depósito' },
    { value: 'armazem', name: 'Armazém' },
    { value: 'hotel', name: 'Hotel' },
    { value: 'motel', name: 'Motel' },
    { value: 'pousada', name: 'Pousada' },
    { value: 'lajecorporativa', name: 'Laje corporativa' },
    { value: 'prediointeiro', name: 'Prédio inteiro' },
    { value: 'casa', name: 'Casa' },
    { value: 'sobrado', name: 'Sobrado' },
    { value: 'sobradoemcondominio', name: 'Sobrado em condomínio' },
    { value: 'barracao', name: 'Barracão' },
    { value: 'terrenoemcondominio', name: 'Terreno em Condomínio' },
  ];